"""Added name column to products

Revision ID: 1bea163978f3
Revises: 89ecd50c5c7f
Create Date: 2024-09-17 11:56:39.992613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bea163978f3'
down_revision: Union[str, None] = '89ecd50c5c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
