"""make gapplicants approved field boolean

Revision ID: adaf0a84eb7f
Revises: 4ef47f180389
Create Date: 2024-08-29 12:30:25.495739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaf0a84eb7f'
down_revision: Union[str, None] = '4ef47f180389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gapplicants', 'approved',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using="approved::boolean",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gapplicants', 'approved',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using="approved::boolean",
               existing_nullable=True)
    # ### end Alembic commands ###
