"""Replace gapplicant approved field with status field

Revision ID: bb9daa72bf9c
Revises: 453d3c26cde5
Create Date: 2024-09-12 13:38:20.002385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9daa72bf9c'
down_revision: Union[str, None] = '453d3c26cde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gapplicants', sa.Column('status', sa.String(), server_default="pending", nullable=False))
    op.drop_column('gapplicants', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gapplicants', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('gapplicants', 'status')
    # ### end Alembic commands ###
