"""added processing flag to products

Revision ID: d504cbe2735b
Revises: 3eb598f39768
Create Date: 2024-10-07 10:57:51.354084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd504cbe2735b'
down_revision: Union[str, None] = '3eb598f39768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('processing', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'processing')
    # ### end Alembic commands ###
