"""Removed generic notes and added specific notes

Revision ID: edf9b773e818
Revises: cf5413fd4d9a
Create Date: 2024-10-25 08:06:24.400709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf9b773e818'
down_revision: Union[str, None] = 'cf5413fd4d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('officer_notes', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('reviewer_notes', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('approver_notes', sa.String(), nullable=True))
    op.drop_column('loan_applications', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('loan_applications', 'approver_notes')
    op.drop_column('loan_applications', 'reviewer_notes')
    op.drop_column('loan_applications', 'officer_notes')
    # ### end Alembic commands ###
